### ISSUE TITLE
Swift support?

### ISSUE THREAD

**Issue by MKGitHub** [tapouillo/BMGlyphLabel#10]
Please add Swift support, Swift is the new kid on the block :-)

**Comment by tapouillo** [comment]
Hi,

Yes indeed :) I will check that in the coming weeks ...

Stéphane

**Comment by MKGitHub** [comment]
Sweet! Please make sure you get the latest version of Swift...

**Comment by neoneye** [comment]
:+1:

**Comment by tapouillo** [comment]
you can use objective-c class in your swift project, so i don't plan to rewrite all in swift (at least not before several weeks/month)

see: http://stackoverflow.com/questions/24002369/how-to-call-objective-c-code-from-swift

**Comment by Domsou** [comment]
As Swift2 is here, are there any news?

**Comment by tapouillo** [comment]
Hi,

I've just uploaded a swift version: https://github.com/tapouillo/BMGlyphLabelSwift

Please note that it has not been fully tested yet, and it's my first time with swift :)
However I tested it on a simulator, it seems to work as expected.

**Comment by neoneye** [comment]
Awesome :+1:
