### ISSUE TITLE
Updated CocoaPod spec, please? Last one is very out of date

### ISSUE THREAD

**Issue by Multiforge** [tapouillo/BMGlyphLabel#12]
Hello,

I'm using BMGlyphLabel in a new project via CocoaPods. However, the latest BMGlyphLabel version available via CocoaPods is 0.1.1, which is very old. Any chance you could create a new 0.1.2 tag and submit a new podspec for it?

Currently this is all that's available:
https://github.com/CocoaPods/Specs/blob/master/Specs/BMGlyphLabel/0.1.1/BMGlyphLabel.podspec.json

Best regards, and thanks for any help.

**Comment by tapouillo** [comment]
Hi, 
sure I will do it shortly, sorry for that...

**Comment by tapouillo** [comment]
it should be done now:
pod trunk info BMGlyphLabel

BMGlyphLabel
    - Versions:
      - 0.1.0 (2014-05-19 21:59:30 UTC)
      - 0.1.1 (2014-05-19 22:05:35 UTC)
      - 0.1.3 (2015-10-09 17:02:21 UTC)
    - Owners:
      - Stéphane Queraud <squeraud@gmail.com>

let me know if there is any problems

**Comment by Multiforge** [comment]
Merci beaucoup! Much appreciated.
