### ISSUE TITLE
Swift

### ISSUE THREAD

**Issue by milanbalaz** [tapouillo/BMGlyphLabel#14]
Hello, If you can make this awesome lib in/for swift language, this will be amazing.
Do you thing, it is possible?

**Comment by tapouillo** [comment]
Hi,

I've just uploaded a swift version: https://github.com/tapouillo/BMGlyphLabelSwift

Please note that it has not been fully tested yet, and it's my first time with swift :)
However I tested it on a simulator, it seems to work as expected.
