### ISSUE TITLE
Instantiate with 'self' rather than 'BMGlyphLabel'

### ISSUE THREAD

**Issue by WarpRulez** [tapouillo/BMGlyphLabel#15]
In the [BMGlyphLabel labelWithText:font:] method, rather than

return [[BMGlyphLabel alloc] initWithText:text font:font];

it should be:

return [[self alloc] initWithText:text font:font];

Else if instantiating a derived class using that method, it will return the wrong kind of class.

**Comment by tapouillo** [comment]
thanks, it is fixed
